name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy -- -D warnings
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo fmt
      run: cargo fmt -- --check
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --release -- --nocapture
  luau-analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup foreman
      uses: Roblox/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Analyze
      run: luau-lsp analyze --settings ./.vscode/settings.json ./conformance/generated
