name: Conformance
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  conformance_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup rokit
      uses: CompeyDev/setup-rokit@v0.1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    - name: Download just
      uses: extractions/setup-just@v3
    - name: Download Protoc
      uses: arduino/setup-protoc@v3
    - name: Run conformance tests
      run: just run-conformance-tests || true
    - name: Check if conformance tests changed
      run: git diff --exit-code conformance/generated
    - name: Check if failing tests changed
      run: git diff --exit-code conformance/failing_tests.txt
