name: Conformance
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  conformance_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup foreman
      uses: Roblox/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    - name: Download just
      run: sudo snap install --edge --classic just
    - name: Download Protoc
      uses: arduino/setup-protoc@v3
    - name: Download protobuf-conformance
      uses: robinraju/release-downloader@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: bufbuild/protobuf-conformance
        extract: true
        out-file-path: conformance_test_runner
        tag: latest
    - name: Move conformance tests
      run: mv ./conformance_test_runner/bin/conformance_test_runner ./conformance/conformance_test_runner
    - name: Run conformance tests
      run: just run-conformance-tests || true
    - name: Check if conformance tests changed
      run: git diff --exit-code conformance/generated
    - name: Check if failing tests changed
      run: git diff --exit-code conformance/failing_tests.txt
